services:
  postgres:
    image: postgres
    container_name: postgres-graphql
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_LISTENING_PORT}:${POSTGRES_LISTENING_PORT}
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data: